strings:
  inputs: "../Localizations/en.lproj"
  outputs:
    - templatePath: strings.stencil
      output: ../Generated/L10n.generated.swift
      params:
        enumName: Localization
# fonts:
#   inputs: "../Fonts"
#   outputs:
#     - templatePath: fonts.stencil
#       output: ../Generated/Fonts.swift
#       params:
#         enumName: Font
xcassets:
  inputs: "../SubsTemplate/Resources/Assets.xcassets"
  outputs:
    - templatePath: assets.stencil
      output: ../Generated/Assets.generated.swift
##############
#
### SubsResources ###
#
##############
strings:
  inputs: "../SubsResources/Sources/SubsResources/Resources/Localizations/en.lproj"
  outputs:
    - templatePath: module.strings.stencil
      output: ../SubsResources/Sources/SubsResources/Generated/L10n.generated.swift
      params:
        enumName: L10n
        publicAccess: true
xcassets:
  inputs: "../SubsResources/Sources/SubsResources/Resources/Assets.xcassets"
  outputs:
    - templatePath: module.assets.stencil
      output: ../SubsResources/Sources/SubsResources/Generated/Assets.generated.swift
      params:
        enumName: Assets
        publicAccess: true
